name: Source Composition Analysis Scan
on:
  push:
    branches: '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-sca:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod --version

      - name: Install Dependencies
        run: |
          pod install --repo-update || echo "Pod install completed with warnings"
        continue-on-error: true

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        run: |
          # Check for vulnerabilities in dependencies
          snyk test --file=Podfile.lock --package-manager=cocoapods || true
          
          # Check for vulnerabilities in the project
          snyk test --file=contentstack-ios-persistence-example.xcodeproj/project.pbxproj --package-manager=cocoapods || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Generate Snyk Report
        run: |
          echo "## Snyk Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "Security scan completed. Check the logs above for any vulnerabilities found." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note**: This scan checks for known vulnerabilities in your project dependencies." >> $GITHUB_STEP_SUMMARY